export const CART_ERROR_CODES = {
  NOT_AUTHENTICATED: "CART_NOT_AUTHENTICATED",
  SELLER_MISMATCH: "CART_SELLER_MISMATCH",
  PRODUCT_UNAVAILABLE: "CART_PRODUCT_UNAVAILABLE",
  QUANTITY_INVALID: "CART_QUANTITY_INVALID",
  STOCK_EXCEEDED: "CART_STOCK_EXCEEDED",
  ITEM_NOT_FOUND: "CART_ITEM_NOT_FOUND",
  NOT_ALLOWED: "CART_NOT_ALLOWED",
  RATE_LIMITED: "CART_RATE_LIMITED",
} as const;

export type CartErrorCode =
  (typeof CART_ERROR_CODES)[keyof typeof CART_ERROR_CODES];

export type CartActionState = {
  error?: string;
  success?: string;
  errorCode?: CartErrorCode;
};
