export const REVIEW_ERROR_CODES = {
  NOT_AUTHENTICATED: "REVIEW_NOT_AUTHENTICATED",
  NOT_CONFIGURED: "REVIEW_NOT_CONFIGURED",
  NOT_ELIGIBLE: "REVIEW_NOT_ELIGIBLE",
  PRODUCT_UNAVAILABLE: "REVIEW_PRODUCT_UNAVAILABLE",
  INVALID_INPUT: "REVIEW_INVALID_INPUT",
  ALREADY_REVIEWED: "REVIEW_ALREADY_REVIEWED",
  NOT_ALLOWED: "REVIEW_NOT_ALLOWED",
  RATE_LIMITED: "REVIEW_RATE_LIMITED",
} as const;

export type ReviewErrorCode =
  (typeof REVIEW_ERROR_CODES)[keyof typeof REVIEW_ERROR_CODES];

export type ReviewActionState = {
  error?: string;
  success?: string;
  errorCode?: ReviewErrorCode;
};
